repos:
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.45
    hooks:
      - id: checkov
        args: ["--quiet"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1 # Usa la versión más reciente
    hooks:
      - id: gitleaks

  - repo: https://github.com/returntocorp/semgrep
    rev: v1.71.0
    hooks:
      - id: semgrep
        args: ["--config=auto"]
